build_from:
  aarch64: ghcr.io/hassio-addons/base/aarch64:13.1.1
  amd64: hub.docker.com/r/thejf/pre-antennas:latest
  armhf: ghcr.io/hassio-addons/base/armhf:13.1.1
  armv7: ghcr.io/hassio-addons/base/armv7:13.1.1
  i386: hub.docker.com/r/thejf/pre-antennas:latest
